version: "2.14.0"

services:
  frontend-meta:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    network_mode: "host"

  sentiment-analysis:
    build:
      context: sentiment_api
      dockerfile: Dockerfile
    ports:
      - "9098:9098"
    network_mode: "host"

  mysql:
    image: "mysql:8-oracle"
    ports:
      - "3306:3306"
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_DATABASE=social_media_database
      - MYSQL_USER=social_media_user
      - MYSQL_PASSWORD=dummypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - "./db-setup/init.sql:/docker-entrypoint-initdb.d/1.sql"
